package permissions;

import java.security.Principal;
import org.jboss.seam.security.permission.PermissionCheck;
import org.jboss.seam.security.Role;
import org.wc.trackrite.users.User;
import org.witchcraft.base.entity.BusinessEntity;

global User user;



rule "CanUserDeleteEntities"
no-loop 
when
  $c : PermissionCheck( )
  $r : Role(name == "admin")
then
  $c.grant();
end     


//by default users should be able to edit their own records 
rule "CanUserEditOwn"
no-loop
dialect "java" 
when
  principal: Principal()
  c : PermissionCheck( action == "edit")
  eval ( ((BusinessEntity)c.getTarget()).getCreatedByUser().getUserName().equals (principal.getName() )  )
then
  System.out.println( c.getAction() + " created by id is : " +  " " + user.getId() );
  c.grant();
end   





