package permissions;

import java.security.Principal;
import org.jboss.seam.security.permission.PermissionCheck;
import org.jboss.seam.security.Role;
import org.wc.trackrite.users.User;
import org.witchcraft.base.entity.BusinessEntity;

global User user;


rule "AllowAllToAdmin"
no-loop 
when
  $r : Role(name == "admin")
  $c : PermissionCheck()
then
  $c.grant();
end 


rule "AllowDelete"
no-loop 
when
  $c : PermissionCheck( action == "archive" )
  $r : Role(name == "admin")
then
  $c.grant();
end 

/*
rule "AllowEdit"
no-loop 
when
  $c : PermissionCheck( action == "edit"  )
  $r : Role(name == "admin")
then
  $c.grant();
end    
*/

rule "AllowView"
no-loop 
when
  $c : PermissionCheck( action == "view"  )
  $r : Role()
then
  $c.grant();
end      


//by default users should be able to edit their own records 
rule "CanUserEditOwn"
no-loop
dialect "java" 
when
  principal: Principal()
  c : PermissionCheck( action == "edit")
  eval ( c.getTarget() == null || (!c.isGranted() && c.getTarget() != null && 
  			 c.getTarget() instanceof BusinessEntity && ((BusinessEntity)c.getTarget()).getCreatedByUser() != null && 
  	 ((BusinessEntity)c.getTarget()).getCreatedByUser().getUserName().equals (principal.getName() ) )  )
then
  //System.out.println( c.getAction() + " created by id is : " +  " " + user.getId() );
  c.grant();
end   




