package permissions;

import java.security.Principal;
import org.jboss.seam.security.permission.PermissionCheck;
import org.jboss.seam.security.Role;

     
//admin should have all previliges     
rule "CanAdminDoEverything"
no-loop 
when
  $c : PermissionCheck( )
  $r : Role(name == "admin")
then
  $c.grant();
end

//dummy rule to hide 'id' from non admins  
/*
rule "CanNonAdminDoEverything"
no-loop
dialect "java"
when
  principal: Principal()
  c : PermissionCheck(  )
  eval (   ! c.getTarget().equals( "id" )  )
then
  c.grant();
end
*/         