/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-jsf2-primefaces-sd:src/main/java/converter/EntityConverterConfig.p.vm.java
 */
package com.company.demo.web.converter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import com.company.demo.domain.Account;
import com.company.demo.domain.Address;
import com.company.demo.domain.Book;
import com.company.demo.domain.Document;
import com.company.demo.domain.Legacy;
import com.company.demo.domain.LegacyPk;
import com.company.demo.domain.Role;
import com.company.demo.domain.more.MoreTypesDemo;
import com.company.demo.repository.AccountRepository;
import com.company.demo.repository.AddressRepository;
import com.company.demo.repository.BookRepository;
import com.company.demo.repository.DocumentRepository;
import com.company.demo.repository.LegacyRepository;
import com.company.demo.repository.RoleRepository;
import com.company.demo.repository.more.MoreTypesDemoRepository;

/**
 * Responsible for creating Entity JSF converters.
 * Each converter provides a 'print' method to convert an entity instance to a friendly string representation (readable by humans...).
 */
@Configuration
public class EntityConverterConfig {

    // -- AccountConverter

    @Autowired
    AccountRepository accountRepository;

    @Bean
    public AccountConverter accountConverter() {
        return new AccountConverter(accountRepository);
    }

    public class AccountConverter extends GenericJsfConverter<Account, String> {
        public AccountConverter(AccountRepository accountRepository) {
            super(accountRepository);
        }

        @Override
        public String print(Account account) {
            return account == null ? "" : account.getUsername();
        }
    }

    // -- AddressConverter

    @Autowired
    AddressRepository addressRepository;

    @Bean
    public AddressConverter addressConverter() {
        return new AddressConverter(addressRepository);
    }

    public class AddressConverter extends GenericJsfConverter<Address, Integer> {
        public AddressConverter(AddressRepository addressRepository) {
            super(addressRepository);
        }

        @Override
        public String print(Address address) {
            return address == null ? "" : address.getStreetName() + "/" + address.getCity();
        }
    }

    // -- BookConverter

    @Autowired
    BookRepository bookRepository;

    @Bean
    public BookConverter bookConverter() {
        return new BookConverter(bookRepository);
    }

    public class BookConverter extends GenericJsfConverter<Book, Integer> {
        public BookConverter(BookRepository bookRepository) {
            super(bookRepository);
        }

        @Override
        public String print(Book book) {
            return book == null ? "" : book.getTitle();
        }
    }

    // -- DocumentConverter

    @Autowired
    DocumentRepository documentRepository;

    @Bean
    public DocumentConverter documentConverter() {
        return new DocumentConverter(documentRepository);
    }

    public class DocumentConverter extends GenericJsfConverter<Document, String> {
        public DocumentConverter(DocumentRepository documentRepository) {
            super(documentRepository);
        }

        @Override
        public String print(Document document) {
            return document == null ? "" : document.getDocumentContentType() + "/" + document.getDocumentFileName();
        }
    }

    // -- LegacyConverter

    @Autowired
    LegacyRepository legacyRepository;

    @Bean
    public LegacyConverter legacyConverter() {
        return new LegacyConverter(legacyRepository);
    }

    public class LegacyConverter extends GenericJsfConverter<Legacy, LegacyPk> {
        public LegacyConverter(LegacyRepository legacyRepository) {
            super(legacyRepository);
        }

        @Override
        public String print(Legacy legacy) {
            return legacy == null ? "" : legacy.getExtraInfo();
        }
    }

    // -- MoreTypesDemoConverter

    @Autowired
    MoreTypesDemoRepository moreTypesDemoRepository;

    @Bean
    public MoreTypesDemoConverter moreTypesDemoConverter() {
        return new MoreTypesDemoConverter(moreTypesDemoRepository);
    }

    public class MoreTypesDemoConverter extends GenericJsfConverter<MoreTypesDemo, Integer> {
        public MoreTypesDemoConverter(MoreTypesDemoRepository moreTypesDemoRepository) {
            super(moreTypesDemoRepository);
        }

        @Override
        public String print(MoreTypesDemo moreTypesDemo) {
            return moreTypesDemo == null ? "" : moreTypesDemo.getNumberInt() + "/" + moreTypesDemo.getNumberLong()
                    + "/" + moreTypesDemo.getNumberDouble();
        }
    }

    // -- RoleConverter

    @Autowired
    RoleRepository roleRepository;

    @Bean
    public RoleConverter roleConverter() {
        return new RoleConverter(roleRepository);
    }

    public class RoleConverter extends GenericJsfConverter<Role, Integer> {
        public RoleConverter(RoleRepository roleRepository) {
            super(roleRepository);
        }

        @Override
        public String print(Role role) {
            return role == null ? "" : role.getRoleName();
        }
    }
}