package permissions;

import java.security.Principal;
import org.jboss.seam.security.permission.PermissionCheck;
import org.jboss.seam.security.Role;

     
rule "CanUserDeleteEntities"
when
  $c : PermissionCheck( )
  $r : Role(name == "admin")
then
   // System.out.println("The PermissionCheck's properties are: " +   "name=" + $c.getName() + ", action=" + $c.getAction()+ ":: " +  $r.getName());
  $c.grant();
end     