
/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

package com.oreon.phonestore.domain.commerce;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Date;
import javax.ws.rs.core.Response;

import javax.persistence.*;
import org.hibernate.validator.*;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import org.apache.solr.analysis.LowerCaseFilterFactory;
import org.apache.solr.analysis.SnowballPorterFilterFactory;
import org.apache.solr.analysis.StandardTokenizerFactory;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.Formula;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.Cascade;

import org.hibernate.search.annotations.AnalyzerDef;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Boost;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Parameter;
import org.hibernate.search.annotations.TokenFilterDef;
import org.hibernate.search.annotations.TokenizerDef;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.IndexedEmbedded;

import org.hibernate.annotations.Filter;

import org.hibernate.validator.constraints.*;
import javax.validation.constraints.*;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.jboss.seam.annotations.Name;

import org.witchcraft.model.support.audit.Auditable;

import org.witchcraft.utils.*;

import org.witchcraft.base.entity.FileAttachment;
import org.witchcraft.base.entity.BaseEntity;

import com.oreon.phonestore.ProjectUtils;

//Impl 

/**
 * Represents the customer class 
 *
 */

@Entity
@Table(name = "customer")
@Filters({@Filter(name = "archiveFilterDef"), @Filter(name = "tenantFilterDef")})
@Cache(usage = CacheConcurrencyStrategy.NONE)
@XmlRootElement
public class Customer extends com.oreon.phonestore.domain.Person
		implements
			java.io.Serializable {
	private static final long serialVersionUID = 246491083L;

	@Column(unique = false)
	protected CustomerType type = com.oreon.phonestore.domain.commerce.CustomerType.STANDARD

	;

	@OneToMany(mappedBy = "customer", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "customer_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<CustomerQuestion> customerQuestions = new HashSet<CustomerQuestion>();

	public void addCustomerQuestion(CustomerQuestion customerQuestion) {

		customerQuestion.setCustomer(this);

		this.customerQuestions.add(customerQuestion);
	}

	@Transient
	public List<com.oreon.phonestore.domain.commerce.CustomerQuestion> getListCustomerQuestions() {
		return new ArrayList<com.oreon.phonestore.domain.commerce.CustomerQuestion>(
				customerQuestions);
	}

	//JSF Friendly function to get count of collections
	public int getCustomerQuestionsCount() {
		return customerQuestions.size();
	}

	@OneToMany(mappedBy = "customer", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	//@JoinColumn(name = "customer_ID", nullable = true)
	@OrderBy("id DESC")
	private Set<CustomerOrder> customerOrders = new HashSet<CustomerOrder>();

	public void addCustomerOrder(CustomerOrder customerOrder) {

		customerOrder.setCustomer(this);

		this.customerOrders.add(customerOrder);
	}

	@Transient
	public List<com.oreon.phonestore.domain.commerce.CustomerOrder> getListCustomerOrders() {
		return new ArrayList<com.oreon.phonestore.domain.commerce.CustomerOrder>(
				customerOrders);
	}

	//JSF Friendly function to get count of collections
	public int getCustomerOrdersCount() {
		return customerOrders.size();
	}

	public void setType(CustomerType type) {
		this.type = type;
	}

	public CustomerType getType() {

		return type;

	}

	public void setCustomerQuestions(Set<CustomerQuestion> customerQuestions) {
		this.customerQuestions = customerQuestions;
	}

	public Set<CustomerQuestion> getCustomerQuestions() {
		return customerQuestions;
	}

	public void setCustomerOrders(Set<CustomerOrder> customerOrders) {
		this.customerOrders = customerOrders;
	}

	public Set<CustomerOrder> getCustomerOrders() {
		return customerOrders;
	}

	@Transient
	public String getDisplayName() {
		try {
			return super.getDisplayName();
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		for (BaseEntity e : customerQuestions) {
			builder.append(e.getDisplayName() + " ");
		}

		for (BaseEntity e : customerOrders) {
			builder.append(e.getDisplayName() + " ");
		}

		return builder.toString();
	}

}
